set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]
set_property PACKAGE_PIN K18 [get_ports {blue[2]}]
set_property PACKAGE_PIN L18 [get_ports {blue[1]}]
set_property PACKAGE_PIN N18 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property PACKAGE_PIN D17 [get_ports {green[3]}]
set_property PACKAGE_PIN G17 [get_ports {green[2]}]
set_property PACKAGE_PIN H17 [get_ports {green[1]}]
set_property PACKAGE_PIN J17 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property PACKAGE_PIN N19 [get_ports {red[3]}]
set_property PACKAGE_PIN J19 [get_ports {red[2]}]
set_property PACKAGE_PIN H19 [get_ports {red[1]}]
set_property PACKAGE_PIN G19 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN P19 [get_ports h_sync]
set_property PACKAGE_PIN R19 [get_ports v_sync]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]


set_property IOSTANDARD LVCMOS33 [get_ports kb_clk]
set_property IOSTANDARD LVCMOS33 [get_ports kb_data]
set_property PACKAGE_PIN C17 [get_ports kb_clk]
set_property PACKAGE_PIN B17 [get_ports kb_data]

set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets kb/red[3]_i_19_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets mov/counter[0]_carry_i_1]

set_property PACKAGE_PIN V17 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports start]

set_property PACKAGE_PIN U16 [get_ports LED1]
set_property PACKAGE_PIN E19 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]

set_property IOSTANDARD LVCMOS33 [get_ports {dir[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dir[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dir[0]}]
set_property PACKAGE_PIN U16 [get_ports {dir[0]}]
set_property PACKAGE_PIN E19 [get_ports {dir[1]}]
set_property PACKAGE_PIN U19 [get_ports {dir[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {an_act[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_act[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_act[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_act[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN V4 [get_ports {an_act[2]}]
set_property PACKAGE_PIN W4 [get_ports {an_act[3]}]
set_property PACKAGE_PIN W7 [get_ports {LED[7]}]

set_property PACKAGE_PIN U4 [get_ports {an_act[1]}]
set_property PACKAGE_PIN U2 [get_ports {an_act[0]}]
set_property PACKAGE_PIN U7 [get_ports {LED[0]}]

set_property PACKAGE_PIN V5 [get_ports {LED[1]}]
set_property PACKAGE_PIN U5 [get_ports {LED[2]}]
set_property PACKAGE_PIN V8 [get_ports {LED[3]}]
set_property PACKAGE_PIN U8 [get_ports {LED[4]}]
set_property PACKAGE_PIN W6 [get_ports {LED[5]}]
set_property PACKAGE_PIN W7 [get_ports {LED[6]}]
